### ISSUE TITLE
Feedback forms with no contact cause error on summary email

### ISSUE THREAD

**Issue by atoff** [VATSIM-UK/core#1145] opened 2018-03-01 22:23 UTC
When a feedback form doesn't have a contact assigned, the summary email job errors.

Either force feedback forms to have a contact assigned, or alter logic in job.

**Comment by NFarrington** [comment] 2018-03-01 22:25
There may be a future use case where a specific form shouldn't have any summary emails sent - therefore, if no contact is assigned, a summary email will not be generated or sent.

Duplicate of #1127 - closing #1127.

**Closed** 2019-10-18 20:20 UTC
Labels: bug, medium, module - feedback
