### ISSUE TITLE
Symfony\Component\Debug\Exception\FatalErrorException in GET /adm/mship/account

### ISSUE THREAD

**Issue by vatsim-uk-pa** [VATSIM-UK/core#650] opened 2016-12-11 21:08 UTC
## Error in VATSIM-UK/Core

**Symfony\Component\Debug\Exception\FatalErrorException** in **GET /adm/mship/account**
Maximum execution time of 30 seconds exceeded

[View on Bugsnag](https://app.bugsnag.com/vatsim-uk/vatsim-uk-slash-core/errors/584dc0521e51a96a2ae89d9e?event_id=584dc05273bf821200f9558e)

## Stacktrace

    bootstrap/cache/compiled.php:6456 - [main]

[View full stacktrace](https://app.bugsnag.com/vatsim-uk/vatsim-uk-slash-core/errors/584dc0521e51a96a2ae89d9e?event_id=584dc05273bf821200f9558e)

**Comment by vatsim-uk-pa** [comment] 2016-12-14 23:20
This issue has been unlinked from an error in Bugsnag
[**Symfony\Component\Debug\Exception\FatalErrorException** in **GET /adm/mship/account**](https://app.bugsnag.com/vatsim-uk/vatsim-uk-slash-core/errors/584dc0521e51a96a2ae89d9e?event_id=584dc05273bf821200f9558e)

**Comment by A-Lawrence** [comment] 2016-12-14 23:20
Duplicate of #582. Unlinked.

**Closed by A-Lawrence** 2016-12-14 23:20 UTC
Labels: bugsnag
