### ISSUE TITLE
Implement check to ensure form has a contact for notifications

### ISSUE THREAD

**Issue by vatsim-uk-pa** [VATSIM-UK/core#1127] opened 2018-02-17 12:52 UTC
## Error in VATSIM-UK/Core (Laravel)

**Symfony\Component\Debug\Exception\FatalThrowableError** in **/var/www/core/current/artisan feedback:summarise --interval=p1d**
Call to a member function notify() on null

[View on Bugsnag](https://app.bugsnag.com/vatsim-uk/vatsim-uk-slash-core-laravel/errors/5a80bce4cd162a0017fd136f?event_id=5a84b164a91f6b0019fe1f18&i=gh&m=ci)

## Stacktrace

    app/Console/Commands/Feedback/GenerateFeedbackSummary.php:56 - App\Console\Commands\Feedback\GenerateFeedbackSummary::handle

[View full stacktrace](https://app.bugsnag.com/vatsim-uk/vatsim-uk-slash-core-laravel/errors/5a80bce4cd162a0017fd136f?event_id=5a84b164a91f6b0019fe1f18&i=gh&m=ci)

*Created by Alex Toff via Bugsnag*

**Comment by NFarrington** [comment] 2018-03-01 22:26
Duplicate of #1145

**Closed by NFarrington** 2018-03-01 22:26 UTC
Labels: bug, bugsnag, medium, production, up-for-grabs, v3.4.3
