### ISSUE TITLE
Symfony\Component\Debug\Exception\FatalErrorException in GET /adm/mship/account

### ISSUE THREAD

**Issue by vatsim-uk-pa** [VATSIM-UK/core#610] opened 2016-12-06 21:58 UTC
## Error in VATSIM-UK/Core

**Symfony\Component\Debug\Exception\FatalErrorException** in **GET /adm/mship/account**
Maximum execution time of 30 seconds exceeded

[View on Bugsnag](https://app.bugsnag.com/vatsim-uk/vatsim-uk-slash-core/errors/584734771e51a96a2ae8521c?event_id=5847347708afad1100b696ae)

## Stacktrace

    bootstrap/cache/compiled.php:6419 - [main]

[View full stacktrace](https://app.bugsnag.com/vatsim-uk/vatsim-uk-slash-core/errors/584734771e51a96a2ae8521c?event_id=5847347708afad1100b696ae)

**Comment by vatsim-uk-pa** [comment] 2016-12-14 23:21
This issue has been unlinked from an error in Bugsnag
[**Symfony\Component\Debug\Exception\FatalErrorException** in **GET /adm/mship/account**](https://app.bugsnag.com/vatsim-uk/vatsim-uk-slash-core/errors/584734771e51a96a2ae8521c?event_id=5848abfff1e44b1100c21dd9)

**Comment by A-Lawrence** [comment] 2016-12-14 23:21
Duplicate of #582

**Closed by A-Lawrence** 2016-12-14 23:21 UTC
Labels: acknowledged, bugsnag, code, refactor
